import type { Context } from "hono";

const spaces = [
  {
    id: "reaction-diffusion-garden",
    title: "Reaction Diffusion Garden",
    path: "/zo-grid?space=reaction-diffusion-garden",
    discipline: "emergent patterns",
    prompt: "A Gray-Scott reaction diffusion sketch where visitors tune feed and kill rates like weather.",
    tags: ["Nature of Code", "shader", "garden"],
    accent: "#20f4b2",
    field: "radial",
    complexity: 91,
  },
  {
    id: "boid-airport",
    title: "Boid Airport",
    path: "/zo-grid?space=boid-airport",
    discipline: "flocking systems",
    prompt: "A flocking runway where hundreds of tiny agents coordinate takeoff without a control tower.",
    tags: ["steering", "flocks", "traffic"],
    accent: "#ffb000",
    field: "flock",
    complexity: 82,
  },
  {
    id: "lorenz-bell-tower",
    title: "Lorenz Bell Tower",
    path: "/zo-grid?space=lorenz-bell-tower",
    discipline: "chaos sculpture",
    prompt: "A bronze bell tower whose ropes trace a Lorenz attractor through fog and midnight light.",
    tags: ["chaos", "3D", "attractor"],
    accent: "#ff5a36",
    field: "orbit",
    complexity: 88,
  },
  {
    id: "cellular-automata-bakery",
    title: "Cellular Automata Bakery",
    path: "/zo-grid?space=cellular-automata-bakery",
    discipline: "grid life",
    prompt: "A tiny bakery where bread, ovens, and customers evolve by cellular automata rules.",
    tags: ["CA", "Game of Life", "simulation"],
    accent: "#f8df72",
    field: "grid",
    complexity: 74,
  },
  {
    id: "fourier-ferry",
    title: "Fourier Ferry",
    path: "/zo-grid?space=fourier-ferry",
    discipline: "epicycle drawing",
    prompt: "A harbor ferry piloted by nested circles that draw coastlines with Fourier epicycles.",
    tags: ["Fourier", "drawing", "water"],
    accent: "#58a6ff",
    field: "waves",
    complexity: 86,
  },
  {
    id: "perlin-weather-station",
    title: "Perlin Weather Station",
    path: "/zo-grid?space=perlin-weather-station",
    discipline: "noise fields",
    prompt: "A living weather wall where Perlin noise becomes wind, cloud cover, and migration maps.",
    tags: ["noise", "terrain", "weather"],
    accent: "#96f550",
    field: "noise",
    complexity: 79,
  },
  {
    id: "maze-worm-cafe",
    title: "Maze Worm Cafe",
    path: "/zo-grid?space=maze-worm-cafe",
    discipline: "path finding",
    prompt: "A neon cafe where hungry maze worms use A* search to find crumbs before the room rearranges.",
    tags: ["A*", "maze", "agents"],
    accent: "#ff65b3",
    field: "maze",
    complexity: 77,
  },
  {
    id: "kinematic-puppet-theater",
    title: "Kinematic Puppet Theater",
    path: "/zo-grid?space=kinematic-puppet-theater",
    discipline: "inverse kinematics",
    prompt: "A puppet theater where tentacle marionettes solve inverse kinematics to chase spotlights.",
    tags: ["IK", "motion", "theater"],
    accent: "#d7b5ff",
    field: "limbs",
    complexity: 84,
  },
  {
    id: "fractal-subway-map",
    title: "Fractal Subway Map",
    path: "/zo-grid?space=fractal-subway-map",
    discipline: "recursive cities",
    prompt: "A subway diagram that recursively grows neighborhoods, transfers, and tiny train myths.",
    tags: ["fractals", "maps", "recursion"],
    accent: "#00d4ff",
    field: "branches",
    complexity: 89,
  },
  {
    id: "genetic-chair-factory",
    title: "Genetic Chair Factory",
    path: "/zo-grid?space=genetic-chair-factory",
    discipline: "evolutionary design",
    prompt: "A chair factory where furniture mutates, competes, and evolves toward comfort and weirdness.",
    tags: ["genetic", "fitness", "design"],
    accent: "#ff8a00",
    field: "genes",
    complexity: 81,
  },
  {
    id: "spring-mass-observatory",
    title: "Spring Mass Observatory",
    path: "/zo-grid?space=spring-mass-observatory",
    discipline: "physics playground",
    prompt: "A mountaintop observatory held together by springs, constraints, and soft-body telescopes.",
    tags: ["physics", "springs", "constraints"],
    accent: "#7df9ff",
    field: "springs",
    complexity: 76,
  },
  {
    id: "markov-ghost-radio",
    title: "Markov Ghost Radio",
    path: "/zo-grid?space=markov-ghost-radio",
    discipline: "generative text",
    prompt: "A haunted radio station where Markov chains remix station IDs into spectral broadcasts.",
    tags: ["Markov", "text", "radio"],
    accent: "#b7ff4a",
    field: "signal",
    complexity: 72,
  },
];

export default async function handler(c: Context) {
  return c.json({
    generatedAt: new Date().toISOString(),
    sourceMood: ["threejs.org gallery", "Zo Pegasus brand", "Nature of Code", "Coding Train challenges"],
    spaces,
  });
}
